# Generated by Django 4.0.5 on 2022-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_information_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
