# Generated by Django 4.0.5 on 2022-11-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_information_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]