# Generated by Django 4.0.5 on 2022-07-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_email',
            new_name='myEmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_password',
            new_name='myPassword',
        ),
    ]
