# Generated by Django 3.2.3 on 2022-09-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0003_auto_20220719_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]