# Generated by Django 3.2.3 on 2022-07-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0002_rename__email_user_myemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='myEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='myPassword',
            new_name='password',
        ),
    ]
