# Generated by Django 4.0.5 on 2022-11-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendproject', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]